### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by aeracode** [aNNiMON/Lightweight-Stream-API#192]
Hello Victor.

I've just encountered a crash after update to 1.2.2 (works ok in 1.2.1):

```
 java.util.NoSuchElementException
        at com.annimon.stream.iterator.LsaIterator.next(LsaIterator.java:20)
        at com.annimon.stream.Stream.match(Stream.java:2425)
        at com.annimon.stream.Stream.anyMatch(Stream.java:2146)
        ..... and line with invocation from my code (see below)
```

Code:

```java
final Supplier<Class<?>> superclasses = traverse(objCls, Class::getSuperclass);
final boolean tagIsNameOfParent = Stream
         .generate(superclasses)
         .takeWhile(Objects::nonNull)
         .map(Class::getSimpleName)
         .anyMatch(tag::equals);
```

JFYI `Class<?> objCls` and `String tag` is guaranteed non-null, implementation of `traverse` :

```
    private static <T> Supplier<T> traverse(T x, UnaryOperator<T> f) {
        final AtomicReference<T> container = new AtomicReference<>(x);
        return () -> AtomicReferenceCompat.updateAndGet(container, f);
    } 
```

Run-time: android api 30. Build with min api 21, desugaring on, proguard off.

**Comment by aeracode** [comment]
GitHub glitched on ticked edit. Close as duplicate of #193 which is more appropriate verstion.
